### ISSUE TITLE
개발단계에서 Swagger 문서를 확인할 수 없는 문제

### ISSUE THREAD

**Issue by 98StarJune** [Deu-Dev-Team/Server#25]
## 개요
현재 테스트 서버에 배포할 경우 Swagger에 정상적으로 접근할 수 없습니다. 실제 배포 시에는 현재와 같이 유지하는 것이 올바르지만 개발 단계에서는 다소 불편을 초래할 수 있습니다.

## 주의사항
추후 릴리즈 시에는 반드시 개발단계에서만 작동하도록 다시 수정해야합니다.

**Comment by yejun614** [comment]
해당 이슈는 제가 맡아서 해결하겠습니다.
