### ISSUE TITLE
DB Migration 요청

### ISSUE THREAD

**Issue by 98StarJune** [Deu-Dev-Team/Server#27]
## 개요
DB 사용을 위해 Entity 모델을 DB테이블로 생성하는 Migration 작업이 필요합니다.

**Comment by yejun614** [comment]
해당 이슈는 #4 이랑 겹치는것 같은데 확인 부탁드립니다.

**Comment by 98StarJune** [comment]
> 해당 이슈는 #4 이랑 겹치는것 같은데 확인 부탁드립니다.

확인했습니다. 이슈 닫겠습니다!
